GET http://localhost:5162

###Cadastro de usuario
POST http://localhost:5162/usuario/cadastrar/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Miguel Viapiana Jung",
    "email": "migvjung@gmail.com",
    "senha": "123456"
}

###Listar usuarios
GET http://localhost:5162/usuario/listar/ HTTP/1.1

### Deletar Usuário
DELETE  http://localhost:5162/usuario/deletar/26baef00-de56-46fc-85d3-00d329757c61 HTTP/1.1

### Cadastro de livro
POST http://localhost:5162/livro/cadastrar/ HTTP/1.1
Content-Type: application/json

{
    "titulo": "Dom Quixote",
    "autor": "Miguel de Cervantes",
    "editora": "Moderna",
    "categoria": "Romance, Sátira, Paródia, Ficção de aventura"
}

###Listar livros
GET http://localhost:5162/livro/listar/ HTTP/1.1

### Buscar livro 
POST http://localhost:5162/livro/buscar/ HTTP/1.1
Content-Type: application/json

{
    "autor": "Miguel de Cervantes"
}

### Deletar livro
DELETE  http://localhost:5162/livro/deletar/26baef00-de56-46fc-85d3-00d329757c61 HTTP/1.1


### Alterar livro
PUT http://localhost:5162/livro/alterar/b1c0c374-7b97-465e-9365-59dd8131aee0
Content-Type: application/json

{
    "titulo" : "Dom",
    "categoria" : "Comédia",
    "autor" : "Anastacio"
}

### Avaliar um livro
POST http://localhost:5162/livro/30200912-0cf1-43c3-9677-577e1167b25e/avaliar/ HTTP/1.1
Content-Type: application/json

{
    "estrelas": 5,
    "usuario": "migvjung@gmail.com"
}


### Comentar um livro
POST http://localhost:5162/livro/30200912-0cf1-43c3-9677-577e1167b25e/comentar/ HTTP/1.1
Content-Type: application/json

{
    "texto": "Este livro é incrível!",
    "usuario": "migvjung@gmail.com"
}

### Registrar um emprestimo
POST http://localhost:5162/emprestimo/registrar/true HTTP/1.1
Content-Type: application/json

{
    "usuarioId": "5d36b7cb-3dac-423a-913b-123df5e3f75c",
    "livroId": "ce8861f4-711b-4788-8152-838d30e79040"
}


### Listar emprestimos
GET http://localhost:5162/emprestimo/listar/ HTTP/1.1


### Registrar Devolução
POST http://localhost:5162/devolucao/registrar/30200912-0cf1-43c3-9677-577e1167b25e HTTP/1.1
Content-Type: application/json

{
    "usuarioId":"5d36b7cb-3dac-423a-913b-123df5e3f75c",
    "livroId": "ce8861f4-711b-4788-8152-838d30e79040"

}

### Listar Devolução
GET http://localhost:5162/devolucao/listar/ HTTP/1.1

### Login de Usuario

POST http://localhost:5162/usuario/login HTTP/1.1
Content-Type: application/json

{
    "email" : "migvjung@gmail.com",
    "senha" : "123456"
}